repo: "stylish-beets"
canvasCourse: "web-design-1"

inherit:
  - naming-restrict-live
  - git-4
  - html
  - css
  - nav-hover

html:
  - path: "index.html"
    has:
      - "header"
      - "header h1"
      - "header nav"
      - "header nav ol"
      - "h2"
      - "p"
      - "blockquote"
      - "blockquote cite"
      - "q"
      - "ul"
      - "dl"
      - "data"
      - "time"
      - "small"
      - "strong"
      - "em"
      - "i"
      - "b"
      - "figure"
      - "figure img"
      - "figure figcaption"
      - "a[href]"
      - "aside"
      - "footer"
      - "link"
    search:
      - "Beetroot"
      - "purple"
      - "Battlestar Galactica"
      - "Chioggia"
      - "Carbohydrates"
      - "Vegetable!"
      - "Wikipedia"
      - "PT\\+Serif"
      - "PT\\+Sans"
      - 'class="'

css:
  - path: "css/main.css"
    has:
      - ["html"]
      - ["img", "width", "100%"]
      - ["a", "text-decoration"]
      - ["a:hover", "text-decoration"]
    search:
      - "PT Serif"
      - "PT Sans"
      - "background-color"
      - "color"
      - "line-height"
      - "font"
      - "font-weight: normal"
      - "text-decoration"
      - "list-style-type"

screenshots:
  - path: "index.html"
    sizes: [608]
